const item=[
  {
  id:'001',
  item_Image: '../images/buy now/1.jpg',
  rating :{
    stars:4.5,
    noOfReviews: 1400,
  },
  company_Name: 'Carton London',
  item_Name: 'Gold Plated Contemporary Kundan Drop Earrings',
  current_price: 606,
  original_Price:1045,
  discount: 42,
},
{
  id:'002',
  item_Image:'images/buy now/2.jpg',
  company_Name: 'CUKOO',
  item_Name: 'Women Padded Halter Neck Swimming Dress',
  current_price: 1507,
  original_Price: 2599,
 
  discount: 42,
   rating: {
      stars: 4.3,
      noOfReviews: 24,
  },
},
{
  id:'003',
  item_Image:'images/buy now/3.jpg',
  company_Name: 'NUEVOSDAMAS',
  item_Name: 'Women Red & White Printed A-Line Knee-Length Skirts',
  original_Price: 1599,
  current_price: 495,
  discount: 69,
   rating: {
      stars: 4.1,
      noOfReviews: 249,
  },
},
{
  id:'004',
  item_Image:'images/buy now/4.jpg',
  company_Name: 'ADIDAS',
  item_Name:'Indian Cricket ODI Jersey',
  original_Price:999,
  current_price:999,
  discount:0,
  rating : {
    stars:4.5,
    noOfReviews:10,
  },
},

{
  id:'005',
  item_Image:'images/buy now/5.jpg',
  company_Name:'Roadster',
  item_Name: 'Pure Cotton T-shirt',
  original_Price: 1399,
        current_price: 489,
        discount: 65,
        rating:{
          stars: 4.2,
          noOfReviews: 3500,
        },
},
{
  id:'006',
  item_Image:'images/buy now/6.jpg',
  company_Name:'Nike',
  item_Name: 'Men ReactX Running Shoes',
  original_Price: 14995,
        current_price: 14995,
        discount: 0,
        rating:{
          stars: 0,
          noOfReviews: 0.0,
},
},
{
  id:'007',
  item_Image:'images/buy now/7.jpg',
  company_Name:'The Indian Garage Co',
  item_Name: 'Men Slim Fit Regular Shorts',
  original_Price: 1599,
        current_price: 639,
        discount: 60,
        rating:{
          stars: 4.2,
          noOfReviews: 388,
},
},
{
  id:'008',
  item_Image:'images/buy now/8.jpg',
  company_Name:'Nivea',
  item_Name: 'Men Fresh Deodrant 150ml',
  original_Price: 285,
        current_price: 142,
        discount: 50,
        rating:{
          stars: 4.2,
          noOfReviews: 5200,
},
},
{
  id:'009',
  item_Image:'images/buy now/9.webp',
  company_Name:'SANSKRUTIHOMES',
  item_Name: 'Women Printed Pure Cotton Night suit',
  original_Price: 2599,
        current_price: 961,
        discount: 63,
        rating:{
          stars: 4.2,
          noOfReviews: 3100,
        }
},
{
  id:'010',
  item_Image:'images/buy now/10.avif',
  company_Name:'SANSKRUTIHOMES',
  item_Name: 'Mandarin Collar Pure Cotton Night suit',
  original_Price: 2499,
        current_price: 975,
        discount: 61,
        rating:{
          stars: 4.3,
          noOfReviews: 240,
},
},
{
  id:'011',
  item_Image:'images/buy now/11.avif',
  company_Name:'HRX by Hrithik Roshan',
  item_Name: 'Women Patterned Rapid-Dry Seamless Yoga Tights',
  original_Price: 1799,
        current_price: 701,
        discount: 61,
        rating:{
          stars: 4.7,
          noOfReviews: 11,
},
},
{
  id:'012',
  item_Image:'images/buy now/12.avif',
  company_Name:'Claura',
  item_Name: 'Women Yellow Cotton Shorts and Top Loungewear Set',
  original_Price: 1299,
        current_price: 740,
        discount: 43,
        rating:{
          stars: 4.7,
          noOfReviews: 6,
},
},
]